# Modified and reordered from Nixpkgs by GrizzlT(2025-06-02)
#
# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=x86_64-unknown-linux-gnu
#
# Metadata:
# - nixpkgs revision: 82b583ba2ba2e5706b35dbe23f31362e62be2a9d
# - hydra build: https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-unknown-linux-gnu.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/249165517
# - instantiated derivation: /nix/store/7g8mrv13mi4zrx66fw0hy4c46j752wfd-stdenv-bootstrap-tools.drv
# - output directory: /nix/store/dw6vr6m5w7ysrdrbs0s5wdgbjmbnr7gx-stdenv-bootstrap-tools
# - build time: Sat, 10 Feb 2024 01:29:55 +0000
{
  function = { mkMinimalPackage, runPlatform, ... }: mkMinimalPackage.onRun {
    name = "bootstrap-files-${runPlatform}";
    version = "2025-06-02";
    drv = {
      outputHashAlgo = "sha256";
      outputHash = "sha256-s4NzD2+37zytVp1Xuu9rSW0Pv5RXFCsKA6tn6LNfOzE=";
      outputHashMode = "recursive";

      builder = /* bash */ ''
        #
        # This build does not actually work.
        # It seems that your store nor your substituters seems to have:
        #
        # ${builtins.placeholder "out"}
        #
        # You can create this path from an already-bootstrapped TODO: corelib
        # and add it to your store.
      '';
    };
  };

  inputs = { pkgs, ... }: {
    inherit (pkgs.self) mkMinimalPackage;
  };

}
